// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vyrcyoushuktdgkvsjiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5cmN5b3VzaHVrdGRna3Zzaml3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MzMyOTQsImV4cCI6MjA3NDUwOTI5NH0.yLOm7ShW_elaneHkFUEBi98qHUOEAlDXWq5Vxw8ttE8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});